call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

set nocompatible
set nowrap
set background=dark
syntax on
colorscheme solarized

set backspace=indent,eol,start
set number " Show line numbers

" Pathogen ********************************************************************

" filetype off
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()
filetype plugin indent on

" Folding *********************************************************************

set foldenable
set foldmethod=syntax
set foldlevelstart=99

" Tabs ************************************************************************
set softtabstop=2
set shiftwidth=2
set tabstop=2
set expandtab

" Searching *******************************************************************
set hlsearch  " highlight all matches in search while searching
set ignorecase " ignore case in searches
nmap <silent> ,/ :nohlsearch<CR> "Clear search highlighting with ,/

" Navigation ******************************************************************
map <C-l> :tabn<CR> "Control-l to navigate to the next tab
map <C-h> :tabp<CR> "Control-h to navigate to the next tab
map <C-n> :tabnew<CR> "Control-n to open new tab

" Copy & Paste ****************************************************************
vmap <C-x> :!pbcopy<CR> "Control-x from visual mode to cut and copy to clipboard
vmap <C-c> :w !pbcopy<CR><CR> "Control-c from visual mode to copy to clipboard

" Status Line *****************************************************************
set showcmd
set ruler " Show ruler

" Filetypes *******************************************************************
au BufNewFile,BufRead *.rhtml set syn=eruby "Ruby HTML
au BufNewFile,BufRead *.ftl set syn=ftl "Freemarker
au BufNewFile,BufRead *.pde set syn=pde "Processing
au BufNewFile,BufRead Rakefile set syn=ruby "Ruby
au BufNewFile,BufRead Gemfile set syn=ruby "Ruby
au BufNewFile,BufRead Vagrantfile set syn=ruby "Ruby
au BufNewFile,BufRead *.json set syn=javascript "JSON

" show trailing whitespace ***************************************************
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
set list

if has("gui_running")
  set guioptions=egmrt
  set guifont=Meslo\ LG\ M\ DZ:h12
endif

"set backupdir=~/.vim/backup
"set directory=~/.vim/backup

set ttymouse=xterm2
set mouse=a

" Better File Opening *********************************************************
set wildmode=list:longest,full

" Use \ as the leader *********************************************************
let mapleader = "\\"
nmap <silent> <leader>s :set spell!<CR>

" Put the cursor at the beginning of the edit after . macro *******************
nmap . .`[

" Show syntax highlighting groups for word under cursor ***********************
nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

" Show whitespace *************************************************************
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
set list

" Ruby helpers ****************************************************************
" Need to move this section to ruby.vim

iabbrev rdebug require 'ruby-debug'; debugger; 1

" Fix up grep.vim
let Grep_Xargs_Options='-0'

" Ctags ****************************************************************
" augroup vimctags
"   autocmd!
"   autocmd BufWritePost *.rb,*.erl silent!ctags -R &
" augroup END

" Highlight long rows **************************************************
highlight OverLength ctermbg=Magenta ctermfg=white guibg=#592929
match OverLength /\%81v./
